import { useState } from "react";
import { loginUser } from "../api";

export default function Login({ logo, onLogin, onRegister, onForgotPassword, onBack, notice }) {
  const [form, setForm] = useState({ email: "", password: "" });
  const [error, setError] = useState("");
  async function submit(event) { event.preventDefault(); if (!form.email || !form.password) return setError("Enter your email and password to continue."); setError(""); try { const result = await loginUser(form); await onLogin(result.user, result.access_token); } catch (requestError) { setError(requestError.message); } }
  return <AuthLayout logo={logo} title="Welcome back" subtitle="Log in to see your financial picture." onBack={onBack}><form onSubmit={submit} className="space-y-4"><Field label="Email address" type="email" value={form.email} onChange={(email) => setForm({ ...form, email })} placeholder="you@example.com" /><Field label="Password" type="password" value={form.password} onChange={(password) => setForm({ ...form, password })} placeholder="Your password" /><div className="text-right"><button type="button" onClick={onForgotPassword} className="text-sm font-bold text-mm-green">Forgot password?</button></div>{notice && <p className="rounded-xl bg-mm-green/10 px-3 py-2 text-sm text-mm-green">{notice}</p>}{error && <p className="rounded-xl bg-red-400/10 px-3 py-2 text-sm text-red-300">{error}</p>}<button className="w-full rounded-xl bg-mm-green py-3.5 font-black text-mm-navy hover:bg-mm-green-light">Log in</button></form><p className="mt-6 text-center text-sm text-mm-muted">New to MoneyMap? <button onClick={onRegister} className="font-bold text-mm-green">Create an account</button></p></AuthLayout>;
}

export function AuthLayout({ logo, title, subtitle, onBack, children }) { return <div className="grid min-h-screen bg-mm-navy text-mm-text lg:grid-cols-2"><section className="hidden flex-col justify-between bg-mm-navy-light p-12 lg:flex"><div className="flex items-center gap-3"><img src={logo} alt="MoneyMap" className="h-11 w-11 rounded-full object-contain" /><p className="text-xl font-black">Money<span className="text-mm-green">Map</span></p></div><div><p className="text-4xl font-black leading-tight">Every choice gets clearer when you can see the whole map.</p><p className="mt-4 max-w-md text-mm-muted">Track, understand, and plan your money from one thoughtful dashboard.</p></div><p className="text-sm text-mm-muted">MoneyMap · See where your money goes</p></section><section className="flex items-center justify-center p-5 sm:p-10"><div className="w-full max-w-md"><button onClick={onBack} className="mb-10 text-sm font-bold text-mm-muted hover:text-mm-text">← Back to home</button><div className="rounded-3xl border border-mm-border bg-mm-card p-7 sm:p-9"><img src={logo} alt="MoneyMap" className="mb-7 h-12 w-12 rounded-full object-contain lg:hidden"/><h1 className="text-3xl font-black">{title}</h1><p className="mt-2 text-mm-muted">{subtitle}</p><div className="mt-8">{children}</div></div></div></section></div>; }
export function Field({ label, type, value, onChange, placeholder }) { return <label className="block text-sm font-bold">{label}<input type={type} value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-mm-border bg-mm-navy px-4 py-3 text-mm-text outline-none placeholder:text-mm-muted focus:border-mm-green" /></label>; }
